"""End-to-end orchestration of a single analyze run.

Runs on a worker thread; every state change is published to the job so the
dashboard reflects progress live rather than at the end.

Stage failures are contained: telemetry, status, and remediation are all
best-effort, because none of them should be able to stop the agent from
repairing code and delivering a branch.
"""

from __future__ import annotations

import shutil
import subprocess
import time
from datetime import UTC, datetime, timedelta
from pathlib import Path

from .analysis import scan_repository
from .cicd import (
    DiagnosisInput,
    assess_repo_health,
    build_incident_report,
    build_log_corpus,
    collect_telemetry,
    diagnose,
    fetch_platform_status,
    remediate,
)
from .cicd.statuspage import PlatformStatus
from .cicd.telemetry import PipelineTelemetry
from .config import Settings
from .github import GitHubClient, GitHubError
from .healing import heal
from .jobstore import Job
from .models import AnalyzeRequest, JobStatus, Phase, Severity
from .redaction import register_secret, scrub
from .repo import changed_since, select_backend
from .scoring import compute_score
from .validation import run_validation

COMMIT_TEMPLATE = """\
fix: autonomous repairs from CI/CD healing agent

Applied {fix_count} automated repair(s) addressing {problem_count} detected
defect(s) across {file_count} file(s).

Categories addressed: {categories}
Validation: {validation}

Generated by the Autonomous CI/CD Healing Agent.
Review this diff before merging.
"""


def _workflow_files_changed(
    root: Path,
    client: GitHubClient | None = None,
    owner: str = "",
    repo: str = "",
    since_hours: int = 72,
) -> list[str]:
    """Workflow files genuinely changed in recent history.

    Filesystem mtime is useless here: a fresh clone stamps every file with the
    checkout time, so an mtime check would report that every workflow just
    changed and push the diagnosis toward a config rollback on every run. The
    answer has to come from commit history -- git log locally, or the commits
    API when there is no git binary.
    """
    workflows_dir = root / ".github" / "workflows"
    if not workflows_dir.is_dir():
        return []

    if (root / ".git").exists() and shutil.which("git"):
        try:
            result = subprocess.run(
                [
                    "git", "log", f"--since={since_hours}.hours",
                    "--name-only", "--pretty=format:", "--",
                    ".github/workflows",
                ],
                cwd=str(root), capture_output=True, text=True, timeout=30,
            )
        except (subprocess.TimeoutExpired, OSError):
            return []
        if result.returncode == 0:
            return sorted(
                {
                    line.strip()
                    for line in result.stdout.splitlines()
                    if line.strip().startswith(".github/workflows/")
                }
            )
        return []

    if client and owner and repo:
        cutoff = datetime.now(UTC) - timedelta(hours=since_hours)
        changed: list[str] = []
        for path in sorted(workflows_dir.glob("*.y*ml")):
            rel = str(path.relative_to(root)).replace("\\", "/")
            try:
                commits = client.list_commits(owner, repo, per_page=1, path=rel)
            except GitHubError:
                continue
            if not commits:
                continue
            raw = ((commits[0].get("commit") or {}).get("author") or {}).get("date")
            stamp = _parse_iso(raw)
            if stamp and stamp >= cutoff:
                changed.append(rel)
        return changed

    return []


def _parse_iso(value: object) -> datetime | None:
    if not isinstance(value, str):
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def run_pipeline(job: Job, request: AnalyzeRequest, settings: Settings) -> None:
    """Execute the full detect -> diagnose -> heal -> validate -> push flow."""
    token = request.github_token or settings.fallback_github_token
    register_secret(token)
    register_secret(settings.fallback_github_token)

    started = time.monotonic()
    workspace = settings.workspace_root / job.id
    client: GitHubClient | None = None
    checkout = None
    problems_before = []
    telemetry = PipelineTelemetry()
    platform_status = PlatformStatus()

    try:
        workspace.mkdir(parents=True, exist_ok=True)
        client = GitHubClient(token=token)

        # ---------------------------------------------------------- CLONE ---
        job.set_phase(
            Phase.CLONING,
            f"Fetching {job.owner}/{job.repo}"
            + (f" at branch '{request.base_branch}'" if request.base_branch else ""),
        )
        backend = select_backend(settings, client, token)
        job.log(f"Repository backend: {backend.name}")
        try:
            checkout = backend.prepare(
                job.owner, job.repo, workspace, request.base_branch
            )
        except Exception as exc:
            job.log(f"Clone failed: {scrub(str(exc))}", level="error")
            job.finish(JobStatus.FAILED, f"Could not fetch repository: {exc}")
            return

        job.base_branch = checkout.base_branch
        job.log(
            f"Checked out {checkout.base_branch} at {checkout.base_sha[:8]} "
            f"(default branch: {checkout.default_branch})"
        )

        # ----------------------------------------------------------- SCAN ---
        job.set_phase(Phase.SCANNING, "Scanning repository for defects")
        scan = scan_repository(checkout.path, max_files=settings.max_repo_files)
        problems_before = list(scan.problems)
        job.files_scanned = scan.files_scanned
        job.languages = scan.inventory.languages if scan.inventory else {}
        job.add_problems(problems_before)
        job.log(
            f"Scanned {scan.files_scanned} file(s); found {len(problems_before)} "
            f"problem(s) using detectors: {', '.join(scan.detectors_run)}"
        )
        if scan.detectors_skipped:
            job.log(f"Detectors skipped: {', '.join(scan.detectors_skipped)}", "warn")

        job.set_repo_health(
            assess_repo_health(checkout.path, client, job.owner, job.repo).to_dict()
        )
        job.bump_progress(35)

        # ------------------------------------------------------ DIAGNOSE ---
        job.set_phase(Phase.DIAGNOSING, "Assessing pipeline and platform health")
        platform_status = fetch_platform_status(settings.status_page_url)
        job.log(
            f"Platform status: {platform_status.description}"
            if platform_status.available
            else f"Platform status unavailable ({platform_status.error})"
        )

        telemetry = collect_telemetry(client, job.owner, job.repo)
        if telemetry.available and telemetry.has_workflows:
            job.log(
                f"Actions telemetry: {telemetry.total_runs} recent run(s), "
                f"{telemetry.failure_rate:.0%} failure rate, queue pressure "
                f"{telemetry.queue_pressure}"
            )
        elif telemetry.error:
            job.log(f"Actions telemetry unavailable: {telemetry.error}", "warn")

        job.set_pipeline_health(
            {
                "platform_status": platform_status.to_dict(),
                "telemetry": telemetry.to_dict(),
            }
        )

        changed_workflows = _workflow_files_changed(
            checkout.path, client, job.owner, job.repo
        )
        critical_count = sum(
            1 for p in problems_before if p.severity is Severity.CRITICAL
        )
        preliminary = run_validation(
            checkout.path, round_index=0, run_tests=False
        )

        diagnosis = diagnose(
            DiagnosisInput(
                telemetry=telemetry,
                platform_status=platform_status,
                log_text=build_log_corpus(telemetry),
                local_critical_problems=critical_count,
                local_validation_failed=not preliminary.passed,
                recent_workflow_change=bool(changed_workflows),
            )
        )
        job.set_diagnosis(diagnosis)
        job.log(
            f"Diagnosis: {diagnosis.failure_class.value.upper()} "
            f"(confidence {diagnosis.confidence:.0%}) -> "
            f"{diagnosis.recommended_action.value}"
        )

        # ------------------------------------------------------- REMEDIATE ---
        failing_run_id = (
            telemetry.job_failures[0].run_id if telemetry.job_failures else None
        )
        try:
            plan = remediate(
                diagnosis,
                checkout.path,
                client,
                job.owner,
                job.repo,
                changed_workflows,
                failing_run_id=failing_run_id,
                execute_pipeline_actions=False,
            )
            for step in plan.steps:
                job.add_remediation(step)
                job.log(f"Remediation [{step.action.value}]: {step.description}")
        except Exception as exc:
            job.log(f"Remediation planning failed: {scrub(str(exc))}", "warn")

        job.bump_progress(50)

        # ----------------------------------------------------------- HEAL ---
        job.set_phase(Phase.HEALING, "Applying repairs")
        max_rounds = request.max_rounds or settings.max_rounds
        validation = None

        for round_index in range(1, max_rounds + 1):
            current = scan_repository(
                checkout.path, max_files=settings.max_repo_files
            ).problems
            if not current:
                job.log(f"Round {round_index}: nothing left to repair.")
                break

            job.log(
                f"Round {round_index}/{max_rounds}: repairing "
                f"{len(current)} problem(s)"
            )

            def progress(rel: str, count: int, _round=round_index) -> None:
                job.log(f"  Round {_round}: AI repairing {rel} ({count} defect(s))")

            outcome = heal(
                checkout.path,
                current,
                settings,
                round_index=round_index,
                use_ai=request.use_ai,
                on_progress=progress,
            )
            for fix in outcome.fixes:
                job.add_fix(fix)
            for note in outcome.notes:
                job.log(f"  {note}", "warn")
            if outcome.ai_skipped_reason:
                job.log(f"  AI tier: {outcome.ai_skipped_reason}", "warn")

            job.set_phase(Phase.VALIDATING, f"Validating round {round_index}")
            validation = run_validation(
                checkout.path,
                round_index=round_index,
                run_tests=request.run_tests,
                allow_test_execution=settings.allow_test_execution,
            )
            job.add_validation(validation)
            job.log(
                f"Round {round_index} validation: "
                f"{'PASSED' if validation.passed else 'FAILED'} - "
                + ", ".join(
                    f"{stage.name}="
                    + ("skip" if stage.skipped else ("pass" if stage.passed else "fail"))
                    for stage in validation.stages
                )
            )

            if validation.passed:
                break
            if not outcome.fixes:
                job.log(
                    "No further repairs were possible; stopping the heal loop.",
                    "warn",
                )
                break
            job.bump_progress(60 + round_index * 5)

        # A repository that needed no repairs still has to be proven green --
        # otherwise "nothing to fix" would be indistinguishable from "never
        # checked", and the run would be scored as if validation had failed.
        if validation is None:
            job.set_phase(Phase.VALIDATING, "Validating baseline")
            validation = run_validation(
                checkout.path,
                round_index=1,
                run_tests=request.run_tests,
                allow_test_execution=settings.allow_test_execution,
            )
            job.add_validation(validation)
            job.log(
                f"Baseline validation: "
                f"{'PASSED' if validation.passed else 'FAILED'} - "
                + ", ".join(
                    f"{stage.name}="
                    + ("skip" if stage.skipped else ("pass" if stage.passed else "fail"))
                    for stage in validation.stages
                )
            )

        # ----------------------------------------------------------- PUSH ---
        job.set_phase(Phase.PUSHING, "Preparing branch")
        changed_files = changed_since(
            checkout.path, checkout.fingerprint, max_files=settings.max_repo_files
        )
        job.log(f"{len(changed_files)} file(s) modified by the agent")

        after = scan_repository(
            checkout.path, max_files=settings.max_repo_files
        ).problems

        if not changed_files:
            job.log("No changes to push.", "warn")
        elif not request.push:
            job.log("Dry run requested; skipping push.", "warn")
        elif not token:
            job.log(
                "No GitHub token supplied; cannot push. Repairs were made "
                "locally but are not published.",
                "warn",
            )
        else:
            job.branch_preview_url = backend.branch_url(
                checkout.owner, checkout.repo, request.branch_name
            )
            categories = sorted({p.kind.value for p in problems_before})
            message = COMMIT_TEMPLATE.format(
                fix_count=len(job.fixes),
                problem_count=len(problems_before),
                file_count=len(changed_files),
                categories=", ".join(categories) or "none",
                validation="passed" if (validation and validation.passed) else "see report",
            )
            try:
                result = backend.publish(
                    checkout,
                    request.branch_name,
                    message,
                    request.author_name,
                    request.author_email
                    or f"{request.author_name.replace(' ', '-').lower()}@users.noreply.github.com",
                    changed_files,
                )
                job.branch_url = result.branch_url
                job.compare_url = result.compare_url
                job.commit_sha = result.commit_sha
                job.log(
                    f"Pushed {len(result.files_committed)} file(s) to "
                    f"'{result.branch}' as {result.commit_sha[:8]}"
                )
                job.log(f"Branch: {result.branch_url}")
            except Exception as exc:
                job.log(f"Push failed: {scrub(str(exc))}", "error")
                push_error = scrub(str(exc))
                if "403" in push_error or "Permission to" in push_error:
                    push_error += (
                        " GitHub rejected the push: use a token with Contents: "
                        "read/write access to this repository, or analyze a fork "
                        "where your account has write permission."
                    )
                job.error = f"Push failed: {push_error}"

        # ------------------------------------------------------- REPORTING ---
        job.set_phase(Phase.REPORTING, "Generating report")
        elapsed = time.monotonic() - started
        score = compute_score(
            problems_before, after, len(job.fixes), elapsed, job.validations
        )
        job.set_score(score)

        job.incident_report = build_incident_report(
            owner=job.owner,
            repo=job.repo,
            branch=request.branch_name if job.branch_url else None,
            diagnosis=job.diagnosis,
            telemetry=telemetry,
            platform_status=platform_status,
            problems=problems_before,
            fixes=job.fixes,
            validations=job.validations,
            remediations=job.remediations,
            elapsed_seconds=elapsed,
            score=score,
            branch_url=job.branch_url,
        )

        resolved = len(problems_before) - len(after)
        if job.error:
            status = JobStatus.PARTIAL
        elif not problems_before and validation and validation.passed:
            status = JobStatus.SUCCEEDED
        elif validation and validation.passed and resolved > 0:
            status = JobStatus.SUCCEEDED
        elif resolved > 0:
            status = JobStatus.PARTIAL
        else:
            status = JobStatus.PARTIAL if job.fixes else JobStatus.FAILED

        job.log(
            f"Complete: {resolved} of {len(problems_before)} problem(s) "
            f"resolved, {len(job.fixes)} fix(es) applied, "
            f"score {score['total']}/100 ({score['grade']})"
        )
        job.finish(status, job.error)

    except Exception as exc:  # noqa: BLE001 - top-level guard for the worker
        job.log(f"Pipeline error: {scrub(str(exc))}", "error")
        job.finish(JobStatus.FAILED, str(exc))
    finally:
        if client:
            client.close()
        shutil.rmtree(workspace, ignore_errors=True)
